Screen('FrameRect',wScreen,[],[sCenter.xCenter-glare.glareDimPix/2, ...
            sCenter.yCenter-glare.glareDimPix/2, ...
            sCenter.xCenter+glare.glareDimPix/2, ...
            sCenter.yCenter+glare.glareDimPix/2],...
            glare.glareWidth)