%% N-back TEST
datasetConfigs = struct();

datasetConfigs.subjects = {'sub-01', 'sub-02', 'sub-03'};

datasetConfigs.folders = {'anat',...
    'func',...
    'func',...
    'func',...
    'func',...
    'func',...
    'anat',...
    'func',...
    'func'};

datasetConfigs.subfolders = {'MPRAGE_p2_1mm_iso_run1',...
    'retinotopia_8bar_Run1',...
    'retinotopia_8bar_Run2',...
    'retinotopia_8bar_Run3',...
    'Glare_Run1',...
    'Glare_Run2',...
    'MPRAGE_p2_1mm_iso_run2',...
    'NoGlare_Run1',...
    'NoGlare_Run2',...
    };

for i = 1:numel(datasetConfigs.folders)
    % create path to data
    datasetConfigs.runs{i} = fullfile(datasetConfigs.folders{i}, datasetConfigs.subfolders{i});
end

datasetConfigs.volumes = [176, 180, 180, 180, 177, 177, 176, 177, 177];
datasetConfigs.TR = 2000;
datasetConfigs.prtPrefix = {'DanielaNF_nBackTask315v1back','DanielaNF195v','DanielaNF195v','DanielaNF195v','DanielaNF195v','DanielaNF195v'};
datasetConfigs.path = 'C:\Users\Bruno\Desktop\NECSUS\source_code\datastructure\NECSUS_data';
datasetConfigs.AnalysisPath = 'C:\Users\Bruno\Desktop\NECSUS\source_code\datastructure\NECSUS_data\ANALYSIS';
%% datasetConfigs.shiftROI = true;
save('Configs_NECSUStest.mat','datasetConfigs')